import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../Components/Navbar";
import Body from "../Components/Body";
import SearchInput from "../Components/SearchInput";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* <Body /> */}
      <SearchInput />
    </div>
  );
};

export default Home;
